spring:
  application:
    name: MovieService
  datasource:
    url: jdbc:mysql://localhost:3306/movieDb
    username: root
    password: bharatmarwah2804

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
